function [masteralgmask,algmask_19_11_19] = algmask
masteralgmask = {...
        'QRS Detection: ECG I',1;...
        'QRS Detection: ECG II',1;...
        'QRS Detection: ECG III',1;...
        'CU Artifact',1;...
        'WUSTL Artifact',1;...
        'Brady Detection',1;...
        'Desat Detection',1;...
        'Apnea Detection with ECG Lead I',1;...
        'Apnea Detection with ECG Lead II',1;...
        'Apnea Detection with ECG Lead III',1;...
        'Apnea Detection with No ECG Lead',1;...
        'Apnea Detection',1;...
        'Periodic Breathing with ECG Lead I',1;...
        'Periodic Breathing with ECG Lead II',1;...
        'Periodic Breathing with ECG Lead III',1;...
        'Periodic Breathing with No ECG Lead',1;...
        'Periodic Breathing',1;...
        'Brady Detection Pete',1;...
        'Desat Detection Pete',1;...
        'Brady Desat',1;...
        'Brady Desat Pete',1;...
        'ABD Pete No ECG',2;...
        'ABD Pete',1;...
        'Save HR in Results',1;...
        'Data Available: Pulse',1;...
        'Data Available: HR',1;...
        'Data Available: SPO2_pct',1;...
        'Data Available: Resp',1;...
        'Data Available: ECG I',1;...
        'Data Available: ECG II',1;...
        'Data Available: ECG III',1};
    
algmask_19_11_19 = [1:3,6:7,12,17:21,23,25:31];